Psonar.projectKey=oficina-backend
sonar.projectName=Oficina Backend - Tech Challenge SOAT Fase 1
sonar.projectVersion=1.0

# Código-fonte de produção (excluir specs e gerados)
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/coverage/**,**/generated/**

# Arquivos de teste (para cruzar com cobertura)
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

# Cobertura — gerada por `npm run test:cov`
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
