apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-backend-config
  namespace: oficina
data:
  NODE_ENV: "production"
  PORT: "3000"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  EMAIL_FROM: "onboarding@resend.dev"
